//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.17 at 04:59:40 PM EST 
//


package extdoc.jsdoc.tplschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}classTemplate"/>
 *         &lt;element ref="{}treeTemplate"/>
 *         &lt;element ref="{}source"/>
 *         &lt;element ref="{}resources"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classTemplate",
    "treeTemplate",
    "source",
    "resources"
})
@XmlRootElement(name = "template")
public class Template {

    @XmlElement(required = true)
    protected ClassTemplate classTemplate;
    @XmlElement(required = true)
    protected TreeTemplate treeTemplate;
    @XmlElement(required = true)
    protected Source source;
    @XmlElement(required = true)
    protected Resources resources;

    /**
     * Gets the value of the classTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link ClassTemplate }
     *     
     */
    public ClassTemplate getClassTemplate() {
        return classTemplate;
    }

    /**
     * Sets the value of the classTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassTemplate }
     *     
     */
    public void setClassTemplate(ClassTemplate value) {
        this.classTemplate = value;
    }

    /**
     * Gets the value of the treeTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link TreeTemplate }
     *     
     */
    public TreeTemplate getTreeTemplate() {
        return treeTemplate;
    }

    /**
     * Sets the value of the treeTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreeTemplate }
     *     
     */
    public void setTreeTemplate(TreeTemplate value) {
        this.treeTemplate = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Resources }
     *     
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resources }
     *     
     */
    public void setResources(Resources value) {
        this.resources = value;
    }

}
